version: '3.6'

services:
  api:
    build: .
    container_name: chess_api
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5001:5000
    environment:
      - FLASK_SQLALCHEMY_DATABASE_URI=postgresql://test:test@chess_db:5432/test
      - FLASK_SECRET_KEY=changeme
    restart: always

  db:
    container_name: chess_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
