
GET http://localhost:5000/users

# CREATE TEST USER

POST http://localhost:5000/users HTTP/1.1
content-type: application/json

{
    "email": "foo@bar.com",
    "password": "bar"
}

# VALID LOGIN

POST http://localhost:5000/login HTTP/1.1
content-type: application/json

{
    "email": "foo@bar.com",
    "password": "bar"
}

# LOGOUT
DELETE http://localhost:5000/login HTTP/1.1

# POST SCORE
POST http://localhost:5000/users/scores HTTP/1.1
content-type: application/json

{
    "score": 200,
    "level": 1
}


# GET HIGH SCORE

GET http://localhost:5000/users/scores/top HTTP/1.1
