name: build-linux

on:
  workflow_dispatch

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend       

    steps:
    - uses: actions/checkout@v3

    - name: Create Executable
      uses: sayyid5416/pyinstaller@main
      with:
        python_ver: '3.9'
        spec: 'frontend/chessgame.spec'
        requirements: 'frontend/requirements.txt'
        upload_exe_with_name: 'chessgame'
        options: --onefile, --name "chessgame", --windowed 
