name: package-frontend

on:
  workflow_dispatch

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            TARGET: macos
            CMD_BUILD: >
              ./frontend/build.sh
              cd dist/
              echo $PWD
              ls -al
              zip -r9 chessgame chessgame.app/
            OUT_FILE_NAME: ./dist/chessgame.zip

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: pip-${{matrix.TARGET}}

    - name: Install dependencies
      run: pip install -r frontend/requirements.txt

    - name: Build with pyinstaller for ${{matrix.TARGET}}
      run: ${{matrix.CMD_BUILD}}

    - uses: actions/upload-artifact@v2
      with:
        name: chessgame
        path: ${{matrix.OUT_FILE_NAME}}
