name: frontend-build

on:
  workflow_dispatch
#   push:
#     tags: [ "v*.*.*" ]  

defaults:
  run:
    shell: bash

env:
  python-version: "3.9"

jobs:
  package:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: write
          
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            platform-name: windows.x64
            build-cmd: |
              ./frontend/build.sh
              echo $PWD
              ls -al
              ls -al dist/
            output-file-name: ./dist/chessgame.exe
            output-file-ext: .exe
          - os: macos-latest
            platform-name: macos.x64
            build-cmd: |
              ./frontend/build.sh
              cd dist/
              echo $PWD
              ls -al
              zip -r9 chessgame chessgame.app/
              ls -al
            output-file-name: ./dist/chessgame.zip
            output-file-ext: .zip
          - os: ubuntu-22.04
            platform-name: linux.x64
            build-cmd: |
              echo "Finding libpng..."
              sudo find / -name "*libpng*16"
              
              echo "Performing build...
              cd frontend
              pyinstaller chessgame.spec
              
              echo "Here are the dist files..."
              ls -al dist/
              echo $PWD
            output-file-name: ./dist/chessgame
            output-file-ext: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set archive name
        run: |
          ARCHIVE_NAME=chessgame-`git describe --always`-${{ matrix.platform-name }}${{ matrix.output-file-ext }}
          echo "Archive name set to: $ARCHIVE_NAME"
          echo "archive-name=$ARCHIVE_NAME" >> $GITHUB_ENV
      - name: Install APT dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libpng16-16
          sudo apt-get install -y libpng-dev
          sudo apt-get install -y \
            tk8.6 libtk8.6 tcl8.6 libtcl8.6 \
            libpng16-16 \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            libssl-dev \
            zlib1g-dev \
            libffi-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libfreetype6-dev \
            libportmidi-dev \
            libjpeg-dev \
            libgdbm-dev \
            uuid-dev \
            upx \
            python3-tk \
            python3-pygame            
          sudo ldconfig
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}    
          
      - name: Install Python dependencies
        run: |
          pip install -r frontend/requirements.txt
          pip install pyinstaller
      - name: Run Build 
        run: ${{matrix.build-cmd}}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{env.archive-name}}
          path: ${{matrix.output-file-name}}      
      # If a tag is pushed then a new archives are uploaded to GitHub Releases automatically.

      - name: Create name for upload release if needed
        run: |
          ls -al dist
          echo "$PWD"
          cp ${{matrix.output-file-name}} ${{env.archive-name}}     
      - name: Upload release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.archive-name }}
